export const spanish_usSpeechcons = [
  "'ámonos",
  "a lo mejor",
  "a mano",
  "a todo dar",
  "aaaah",
  "abracadabra",
  "achú",
  "aguas",
  "ah ya ja",
  "ahorita",
  "ahí nos vemos",
  "ajá",
  "al ratito",
  "alrighty",
  "alto",
  "alto ahí",
  "ande",
  "apostamos",
  "argh",
  "arriba las manos",
  "arriba, abajo al centro y pa'dentro",
  "así mero",
  "así que chiste",
  "auch",
  "auchis",
  "auxilio",
  "aw",
  "awesome",
  "ay",
  "ay ay ay",
  "ay caramba",
  "ay caray",
  "ay no",
  "ay ternurita",
  "ay, que susto",
  "basta",
  "bien",
  "bla bla bla",
  "bonitas vacaciones",
  "bonito día",
  "bonito fin",
  "boo",
  "boo hoo",
  "bravo",
  "bu",
  "buah",
  "buen día",
  "buen fin de semana",
  "buen inicio de semana",
  "buen provecho",
  "buen viaje",
  "buena suerte",
  "buenas noches",
  "buenas tardes",
  "bueno",
  "buenos días",
  "bummer",
  "buum",
  "carajo",
  "chale",
  "chance y sí",
  "cheer up",
  "cheers",
  "chido",
  "chidísimo",
  "chirrín conchín",
  "chulada",
  "chuta",
  "cierra los ojos",
  "claaaro",
  "claro",
  "claro que no",
  "claro que sí",
  "como andas?",
  "con que sí, ¿eh?",
  "con un carajo",
  "cuidado",
  "cuidado ¿eh?",
  "córrele",
  "da igual",
  "de lujo",
  "de nada",
  "de ninguna manera",
  "de plano",
  "de super lujo",
  "de veras",
  "diablos",
  "dime la verdad",
  "dude",
  "dímelo a mí caray",
  "eehum",
  "en hora buena",
  "en un ratito",
  "er",
  "eso es todo",
  "estás queriendo",
  "exactamente",
  "exacto",
  "fabuloso",
  "faltaba más",
  "fantástico",
  "felices fiestas",
  "felicidades",
  "feliz año nuevo",
  "feliz cumpleaños",
  "feliz navidad",
  "fenomenal",
  "fiuugh",
  "fondo",
  "fuchi",
  "fúchila",
  "gacho",
  "gachísimo",
  "gee",
  "good afternoon",
  "good evening",
  "good luck",
  "good morning",
  "good night",
  "goodbye",
  "gosh",
  "gotcha",
  "great",
  "guácala",
  "había una vez…",
  "hasta al rato",
  "hasta crees",
  "hasta la vista, baby",
  "hasta luego",
  "hasta mañana",
  "hasta más tarde",
  "hasta pronto",
  "hasta que se te hizo",
  "hasta que te animas",
  "hasta que te dignas",
  "high five",
  "hurra",
  "ja",
  "ja, ja",
  "je",
  "je, je",
  "je, je, je",
  "jeez",
  "jijijiji",
  "jo, jo",
  "just kidding",
  "knock knock",
  "llévelo, llévelo",
  "lo lamento",
  "lo lamento mucho",
  "lo mismo da",
  "lo siento",
  "lo siento mucho",
  "lo veo y no lo creo",
  "lotería",
  "lástima",
  "maldición",
  "maldita sea",
  "mamma mía",
  "me cachaste",
  "me chifa",
  "me da mucha pena",
  "me estás cotorreando",
  "me la debes eh",
  "me las vas a pagar",
  "me lo imaginaba",
  "meow",
  "mira no más",
  "mmm",
  "muchas felicidades",
  "mucho cuidado",
  "nada",
  "nada de nada",
  "nah",
  "neeh",
  "nel",
  "ni en cuenta",
  "ni idea",
  "ni idea, eh",
  "ni modo",
  "ni quien te crea",
  "ni tú ni yo",
  "no",
  "no hay de qué",
  "no hay problema",
  "no way",
  "oh dear",
  "oh well",
  "oops",
  "ouch",
  "phew",
  "really",
  "spoiler alert",
  "there there",
  "touchdown",
  "touché",
  "uh huh",
  "uish",
  "um",
  "urrg",
  "voila",
  "well",
  "well done",
  "woof",
  "wow",
  "yay",
  "yeah",
  "yes",
  "yikes",
  "you bet",
  "¿cómo no?",
  "¿eeeh?",
  "¿es en serio?",
  "¿interrumpo?",
  "Ánimo",
  "épale",
] as const;
export type spanish_usSpeechcons = (typeof spanish_usSpeechcons)[number];
